"""add phone field and auto merchant support

Revision ID: 004
Revises: 003
Create Date: 2025-10-29 22:55:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '004'
down_revision: str | None = '003'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add phone field to users table
    op.add_column('users', sa.Column('phone', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    
    # Make email nullable for SMS-only enrollment
    op.alter_column('users', 'email',
                   existing_type=sa.String(length=255),
                   nullable=True,
                   existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email',
                   existing_type=sa.String(length=255),
                   nullable=False,
                   existing_nullable=True)
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_column('users', 'phone')
    # ### end Alembic commands ###

